CORRECION_LLENADO = """
SELECT
    fecha_hora,
    NOMBRE_COMPLETO,
    ID,
    CELULAR,
    EMAIL,
    PAIS,
    INVITADO_POR,
    ID_TWOGETHER,
    ROW_NUMBER() OVER (PARTITION BY ID, ID_TWOGETHER ORDER BY fecha_hora) AS LLENADO_INCORRECTO,
    ROW_NUMBER() OVER (PARTITION BY ID ORDER BY fecha_hora) AS USUARIOS_ENIDTWOGETHER
FROM frame
"""

CONTACTOS = """

WITH USUARIOS_VALIDOS AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY ID_TWOGETHER ORDER BY fecha_hora) AS CANTIDAD_CONMISMOID
    FROM frame_corregido
    WHERE LLENADO_INCORRECTO = 1
)

SELECT 
    fecha_hora,
    ID,
    ID_TWOGETHER,
    PAIS,
    LLENADO_INCORRECTO,
    USUARIOS_ENIDTWOGETHER,
    CANTIDAD_CONMISMOID,
    CASE WHEN USUARIOS_ENIDTWOGETHER > 1 THEN 'CONTACTAR_USUARIO_EN_+2ID_TWOGETHER'
        ELSE 'NO_CONTACTAR' END AS VALIDACION_LLENADO,
    CASE WHEN CANTIDAD_CONMISMOID > 2 THEN 'CONTACTAR_USUARIO_ENID_CON+2_PERSONAS'
        ELSE 'NO_CONTACTAR' END AS VALIDACION_IDTWOGETHER,
    NOMBRE_COMPLETO,
    CELULAR,
    EMAIL,
    INVITADO_POR
FROM USUARIOS_VALIDOS
ORDER BY ID, ID_TWOGETHER;
"""
